#!/bin/bash
xhost +local:docker
docker run --rm -itd -h hwpviewer --name hwpviewer \
    -v /run/user/1000:/run/user/1000 \
    -v /dev:/dev \
    -v /etc/localtime:/etc/localtime:ro \
    -v /tmp/.X11-unix:/tmp/.X11-unix:ro \
    --privileged \
    --ipc=host --shm-size=256m --net=host \
    -v $HOME:/home/hnc \
    -e DISPLAY=unix$DISPLAY \
    -e XDG_RUNTIME_DIR=/run/user/1000 \
    -e PULSE_SERVER=pulseaudio \
    -e "GTK_IM_MODULE=nimf" \
    -e "XMODIFIERS=@im=nimf" \
    -e "QT_IM_MODULE=nimf" \
    -e "LANG=C.UTF-8" \
    -e "LANGUAGE=C.UTF-8" \
    hnc /opt/hnc/hofficeviewer11/Bin/hwpviewer

